# Generated by Django 5.1.4 on 2025-01-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
        ('resort_meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort_meals',
            name='refrence_resort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resort.resort'),
        ),
    ]
