# Generated by Django 5.1.4 on 2024-12-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anotherr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherr',
            name='age',
            field=models.IntegerField(),
        ),
    ]
