# Generated by Django 5.1.4 on 2025-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='resort/')),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.IntegerField()),
                ('room', models.IntegerField()),
                ('bed', models.IntegerField()),
            ],
        ),
    ]
